name: Deploy to EC2

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd ~/my-backend || exit 1

          echo "Pulling latest code..."
          git fetch origin main && git reset --hard origin/main

          echo "Building Docker image..."
          sudo docker build -t my-backend .

          echo "Stopping old container..."
          sudo docker stop backend || true
          sudo docker rm backend || true

          echo "Running new container..."
          sudo docker run -d --name backend -p 3000:3000 my-backend

          echo "✅ Deployment complete!"
          EOF

